name: Deploy

on:
  push:
    branches:
      - main
    paths:
     - '.github/workflows/main.yaml'
     - 'packages/server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jda-netlify" #Must be unique in Heroku
          heroku_email: "vin.miquel@gmail.com"